[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
aes-soft = { path = "../../../aes/aes-soft" }
aes = { path = "../../../aes/aes" }
aesni = { path = "../../../aes/aesni", features = ["ctr"] }
blowfish = { path = "../../../blowfish" }
block-modes = { path = "../../../block-modes" }
cast5 = { path = "../../../cast5" }
des = { path = "../../../des" }
kuznyechik = { path = "../../../kuznyechik" }
magma = { path = "../../../magma" }
rc2 = { path = "../../../rc2" }
twofish = { path = "../../../twofish" }
block-cipher-trait = { git = "https://github.com/mesalock-linux/rustcrypto-traits-sgx", features = ["dev"] }
stream-cipher = { git = "https://github.com/mesalock-linux/rustcrypto-traits-sgx", features = ["dev"] }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_tstd = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_tunittest = {rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git" }
