[package]
name = "blowfish"
version = "0.4.0"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "Blowfish block cipher"
documentation = "https://docs.rs/blowfish"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "blowfish", "block-cipher"]
categories = ["cryptography", "no-std"]

[dependencies]
block-cipher-trait = { git = "https://github.com/mesalock-linux/rustcrypto-traits-sgx" }
byteorder = { git = "https://github.com/mesalock-linux/byteorder-sgx" }
opaque-debug = "0.2"

[dev-dependencies]
#block-cipher-trait = { version = "0.6", features = ["dev"] }

[features]
bcrypt = []

[badges]
travis-ci = { repository = "RustCrypto/block-ciphers" }
