[package]
name = "sm4"
version = "0.0.1"
authors = ["andelf <andelf@gmail.com>"]
license = "Apache-2.0 OR MIT"
description = "SM4 block cipher algorithm"
documentation = "https://docs.rs/sm4"
repository = "https://github.com/RustCrypto/block-ciphers/tree/master/rc2"
readme = "README.md"
keywords = ["crypto", "sm4", "block-cipher"]
categories = ["cryptography"]

[dependencies]
block-cipher-trait = "0.6"
byteorder = { version = "1", default-features = false }
opaque-debug = "0.2"

[dev-dependencies]
block-cipher-trait = { version = "0.6", features = ["dev"] }

[badges]
maintenance = { status = "experimental" }
