[package]
name = "serpent"
version = "0.0.1"
authors = ["Blocs <jonathan@cryptoblocs.fr>"]
license = "Apache-2.0 AND MIT"
readme = "README.md"
edition = "2018"
description = "Serpent block cipher : A Candidate Block Cipher for the Advanced Encryption Standard (AES)"
documentation = "https://docs.rs/serpent"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "serpent", "block-cipher"]
categories = ["cryptography", "no-std"]

[dependencies]
byteorder = { version = "1", default-features = false }
block-cipher-trait = "0.6"
opaque-debug = "0.2"

[dev-dependencies]
block-cipher-trait = { version = "0.6", features = ["dev"] }

[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "RustCrypto/block-ciphers" }
