[package]
name = "kuznyechik"
version = "0.3.0"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "Kuznyechik (GOST R 34.12-2015) block cipher"
documentation = "https://docs.rs/kuznyechik"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "kuznyechik", "gost", "block-cipher"]
categories = ["cryptography", "no-std"]

[dependencies]
block-cipher-trait = { git = "https://github.com/mesalock-linux/rustcrypto-traits-sgx" }
opaque-debug = "0.2"

[dev-dependencies]
#block-cipher-trait = { version = "0.6", features = ["dev"] }

[badges]
travis-ci = { repository = "RustCrypto/block-ciphers" }
