[package]
name = "twofish"
version = "0.2.0"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "Twofish block cipher"
documentation = "https://docs.rs/twofish"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "twofish", "block-cipher"]
categories = ["cryptography", "no-std"]

[dependencies]
byteorder = { git = "https://github.com/mesalock-linux/byteorder-sgx" }
block-cipher-trait = { git = "https://github.com/mesalock-linux/rustcrypto-traits-sgx" }
opaque-debug = "0.2"

[dev-dependencies]
#block-cipher-trait = { version = "0.6", features = ["dev"] }

[badges]
travis-ci = { repository = "RustCrypto/block-ciphers" }
